project:
  type: website
  output-dir: docs

website:
  title: "Apps"
  navbar:
    background: danger
    # left:
    #   - href: index.qmd
    #     text: Home

format:
  html:
    theme: materia  # Puedes cambiar por otro que prefieras
